/*
 * This source file was generated by the Gradle 'init' task
 */
package com.fntsoftware;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.xml.validation.XmlValidatorFactory;

import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;

@SpringBootTest
class AppTest {

    @Value("classpath:camel-spring-4.8.3.xsd")
    org.springframework.core.io.Resource camelSchema;

    @Test
    void createXmlValidator() throws IOException {
        assertDoesNotThrow(() -> XmlValidatorFactory.createValidator(
                camelSchema,
                XmlValidatorFactory.SCHEMA_W3C_XML));
    }
}
